/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingMenuRouteImport } from './routes/wedding-menu'
import { Route as ReligiousMenuRouteImport } from './routes/religious-menu'
import { Route as Portal84kx9AdminPanelRouteImport } from './routes/portal-84kx9-admin-panel'
import { Route as PartiesMenuRouteImport } from './routes/parties-menu'
import { Route as AdminSignupRouteImport } from './routes/admin-signup'
import { Route as AdminResetPasswordRouteImport } from './routes/admin-reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin-forgot-password'
import { Route as ContactUsRouteImport } from './routes/ContactUs'
import { Route as AboutUsRouteImport } from './routes/AboutUs'
import { Route as IndexRouteImport } from './routes/index'

const WeddingMenuRoute = WeddingMenuRouteImport.update({
  id: '/wedding-menu',
  path: '/wedding-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReligiousMenuRoute = ReligiousMenuRouteImport.update({
  id: '/religious-menu',
  path: '/religious-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const Portal84kx9AdminPanelRoute = Portal84kx9AdminPanelRouteImport.update({
  id: '/portal-84kx9-admin-panel',
  path: '/portal-84kx9-admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesMenuRoute = PartiesMenuRouteImport.update({
  id: '/parties-menu',
  path: '/parties-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin-signup',
  path: '/admin-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin-reset-password',
  path: '/admin-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin-forgot-password',
  path: '/admin-forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/ContactUs',
  path: '/ContactUs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/AboutUs',
  path: '/AboutUs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AboutUs': typeof AboutUsRoute
  '/ContactUs': typeof ContactUsRoute
  '/admin-forgot-password': typeof AdminForgotPasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-reset-password': typeof AdminResetPasswordRoute
  '/admin-signup': typeof AdminSignupRoute
  '/parties-menu': typeof PartiesMenuRoute
  '/portal-84kx9-admin-panel': typeof Portal84kx9AdminPanelRoute
  '/religious-menu': typeof ReligiousMenuRoute
  '/wedding-menu': typeof WeddingMenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AboutUs': typeof AboutUsRoute
  '/ContactUs': typeof ContactUsRoute
  '/admin-forgot-password': typeof AdminForgotPasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-reset-password': typeof AdminResetPasswordRoute
  '/admin-signup': typeof AdminSignupRoute
  '/parties-menu': typeof PartiesMenuRoute
  '/portal-84kx9-admin-panel': typeof Portal84kx9AdminPanelRoute
  '/religious-menu': typeof ReligiousMenuRoute
  '/wedding-menu': typeof WeddingMenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AboutUs': typeof AboutUsRoute
  '/ContactUs': typeof ContactUsRoute
  '/admin-forgot-password': typeof AdminForgotPasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-reset-password': typeof AdminResetPasswordRoute
  '/admin-signup': typeof AdminSignupRoute
  '/parties-menu': typeof PartiesMenuRoute
  '/portal-84kx9-admin-panel': typeof Portal84kx9AdminPanelRoute
  '/religious-menu': typeof ReligiousMenuRoute
  '/wedding-menu': typeof WeddingMenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AboutUs'
    | '/ContactUs'
    | '/admin-forgot-password'
    | '/admin-login'
    | '/admin-reset-password'
    | '/admin-signup'
    | '/parties-menu'
    | '/portal-84kx9-admin-panel'
    | '/religious-menu'
    | '/wedding-menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AboutUs'
    | '/ContactUs'
    | '/admin-forgot-password'
    | '/admin-login'
    | '/admin-reset-password'
    | '/admin-signup'
    | '/parties-menu'
    | '/portal-84kx9-admin-panel'
    | '/religious-menu'
    | '/wedding-menu'
  id:
    | '__root__'
    | '/'
    | '/AboutUs'
    | '/ContactUs'
    | '/admin-forgot-password'
    | '/admin-login'
    | '/admin-reset-password'
    | '/admin-signup'
    | '/parties-menu'
    | '/portal-84kx9-admin-panel'
    | '/religious-menu'
    | '/wedding-menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSignupRoute: typeof AdminSignupRoute
  PartiesMenuRoute: typeof PartiesMenuRoute
  Portal84kx9AdminPanelRoute: typeof Portal84kx9AdminPanelRoute
  ReligiousMenuRoute: typeof ReligiousMenuRoute
  WeddingMenuRoute: typeof WeddingMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-menu': {
      id: '/wedding-menu'
      path: '/wedding-menu'
      fullPath: '/wedding-menu'
      preLoaderRoute: typeof WeddingMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/religious-menu': {
      id: '/religious-menu'
      path: '/religious-menu'
      fullPath: '/religious-menu'
      preLoaderRoute: typeof ReligiousMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-84kx9-admin-panel': {
      id: '/portal-84kx9-admin-panel'
      path: '/portal-84kx9-admin-panel'
      fullPath: '/portal-84kx9-admin-panel'
      preLoaderRoute: typeof Portal84kx9AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties-menu': {
      id: '/parties-menu'
      path: '/parties-menu'
      fullPath: '/parties-menu'
      preLoaderRoute: typeof PartiesMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-signup': {
      id: '/admin-signup'
      path: '/admin-signup'
      fullPath: '/admin-signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reset-password': {
      id: '/admin-reset-password'
      path: '/admin-reset-password'
      fullPath: '/admin-reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-forgot-password': {
      id: '/admin-forgot-password'
      path: '/admin-forgot-password'
      fullPath: '/admin-forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContactUs': {
      id: '/ContactUs'
      path: '/ContactUs'
      fullPath: '/ContactUs'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AboutUs': {
      id: '/AboutUs'
      path: '/AboutUs'
      fullPath: '/AboutUs'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSignupRoute: AdminSignupRoute,
  PartiesMenuRoute: PartiesMenuRoute,
  Portal84kx9AdminPanelRoute: Portal84kx9AdminPanelRoute,
  ReligiousMenuRoute: ReligiousMenuRoute,
  WeddingMenuRoute: WeddingMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
